apiVersion: apps/v1
kind: Deployment
metadata:
  name: tradewisenexus-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tradewisenexus-frontend
  template:
    metadata:
      labels:
        app: tradewisenexus-frontend
    spec:
      containers:
        - name: frontend
          image: tradewise-nexus-tradewisenexus-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
